export const EMPLOYEE_LOGIN_REQUEST = "EMPLOYEE_LOGIN_REQUEST"
export const EMPLOYEE_LOGIN_SUCCESS = "EMPLOYEE_LOGIN_SUCCESS"
export const EMPLOYEE_LOGIN_FAIL = "EMPLOYEE_LOGIN_FAIL"

export const EMPLOYEE_REGISTER_REQUEST = "EMPLOYEE_REGISTER_REQUEST"
export const EMPLOYEE_REGISTER_SUCCESS = "EMPLOYEE_REGISTER_SUCCESS"
export const EMPLOYEE_REGISTER_FAIL = "EMPLOYEE_REGISTER_FAIL"

export const EMPLOYEE_LOGOUT = "EMPLOYEE_LOGOUT"

export const EMPLOYEE_GET_STAT_REQUEST = "EMPLOYEE_GET_STAT_REQUEST"
export const EMPLOYEE_GET_STAT_SUCCESS = "EMPLOYEE_GET_STAT_SUCCESS"
export const EMPLOYEE_GET_STAT_FAIL = "EMPLOYEE_GET_STAT_FAIL"
