export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST"
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL"

export const GET_EMPLOYE_PRODUCT_REQUEST = "GET_EMPLOYE_PRODUCT_REQUEST"
export const GET_EMPLOYE_PRODUCT_SUCCESS = "GET_EMPLOYE_PRODUCT_SUCCESS"
export const GET_EMPLOYE_PRODUCT_FAIL = "GET_EMPLOYE_PRODUCT_FAIL"

export const DETAILS_EMPLOYE_PRODUCT_REQUEST = "DETAILS_EMPLOYE_PRODUCT_REQUEST"
export const DETAILS_EMPLOYE_PRODUCT_SUCCESS = "DETAILS_EMPLOYE_PRODUCT_SUCCESS"
export const DETAILS_EMPLOYE_PRODUCT_FAIL = "DETAILS_EMPLOYE_PRODUCT_FAIL"

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL"

export const UPDATE_IMAGE_REQUEST = "UPDATE_IMAGE_REQUEST" 
export const UPDATE_IMAGE_SUCCESS = "UPDATE_IMAGE_SUCCESS" 
export const UPDATE_IMAGE_FAIL = "UPDATE_IMAGE_FAIL" 

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL"